# fly.toml file generated for breedfind on 2022-09-14T22:48:30+08:00

app = "breedfind"

[env]
  HTTP_ADDR = ":5900"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
